// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/item/Article.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    CommitMap: typeof import('./src/components/CommitMap.vue')['default']
    Item: typeof import('./src/components/item/index.vue')['default']
    'Majesticons:heartLine': typeof import('~icons/majesticons/heart-line')['default']
    'MaterialSymbols:articleOutline': typeof import('~icons/material-symbols/article-outline')['default']
    'MaterialSymbols:locationOnOutlineRounded': typeof import('~icons/material-symbols/location-on-outline-rounded')['default']
    Meta: typeof import('./src/components/item/Meta.vue')['default']
    Moment: typeof import('./src/components/item/Moment.vue')['default']
    PageSide: typeof import('./src/components/PageSide.vue')['default']
    'Ri:contrast2Line': typeof import('~icons/ri/contrast2-line')['default']
    'Ri:searchLine': typeof import('~icons/ri/search-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagList: typeof import('./src/components/TagList.vue')['default']
    'Uil:commentAltDots': typeof import('~icons/uil/comment-alt-dots')['default']
  }
}
