// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'AkarIcons:statisticUp': typeof import('~icons/akar-icons/statistic-up')['default']
    Article: typeof import('./src/components/item/Article.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    'Bi:emojiSmile': typeof import('~icons/bi/emoji-smile')['default']
    'Bi:emojiSunglasses': typeof import('~icons/bi/emoji-sunglasses')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    CommitMap: typeof import('./src/components/CommitMap.vue')['default']
    'Entypo:triangleLeft': typeof import('~icons/entypo/triangle-left')['default']
    'Entypo:triangleRight': typeof import('~icons/entypo/triangle-right')['default']
    'Ic:baselineRemoveRedEye': typeof import('~icons/ic/baseline-remove-red-eye')['default']
    'Ic:baselineSkipNext': typeof import('~icons/ic/baseline-skip-next')['default']
    'Ic:baselineSkipPrevious': typeof import('~icons/ic/baseline-skip-previous')['default']
    'Ic:twotoneArrowRight': typeof import('~icons/ic/twotone-arrow-right')['default']
    Input: typeof import('./src/components/common/Input.vue')['default']
    Item: typeof import('./src/components/item/index.vue')['default']
    KInput: typeof import('./src/components/common/kInput.vue')['default']
    'Majesticons:heartLine': typeof import('~icons/majesticons/heart-line')['default']
    'MaterialSymbols:articleOutline': typeof import('~icons/material-symbols/article-outline')['default']
    'MaterialSymbols:locationOnOutlineRounded': typeof import('~icons/material-symbols/location-on-outline-rounded')['default']
    'MaterialSymbols:lockOutline': typeof import('~icons/material-symbols/lock-outline')['default']
    'Mdi:calendarWeekBegin': typeof import('~icons/mdi/calendar-week-begin')['default']
    Meta: typeof import('./src/components/item/Meta.vue')['default']
    'Mingcute:momentLine': typeof import('~icons/mingcute/moment-line')['default']
    Moment: typeof import('./src/components/item/Moment.vue')['default']
    MyInput: typeof import('./src/components/common/MyInput.vue')['default']
    'Ooui:previousLtr': typeof import('~icons/ooui/previous-ltr')['default']
    'Ooui:previousRtl': typeof import('~icons/ooui/previous-rtl')['default']
    PageSide: typeof import('./src/components/PageSide.vue')['default']
    'Ph:calendarBlankFill': typeof import('~icons/ph/calendar-blank-fill')['default']
    'Ph:lock': typeof import('~icons/ph/lock')['default']
    'Ph:lockLight': typeof import('~icons/ph/lock-light')['default']
    'Ri:contrast2Line': typeof import('~icons/ri/contrast2-line')['default']
    'Ri:searchLine': typeof import('~icons/ri/search-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'Tabler:lock': typeof import('~icons/tabler/lock')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    'Uil:commentAltDots': typeof import('~icons/uil/comment-alt-dots')['default']
  }
}
